apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-config
  namespace: llm-backend
data:
  LLM_NAME: "qwen2.5:0.5b"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-config
  namespace: llm-model
data:
  LLM_NAME: "qwen2.5:0.5b"