apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend    # service name
  namespace: llm-frontend   # namespace name
  # annotations:
  #   argocd-image-updater.argoproj.io/image-list: frontend=ghcr.io/my-org/frontend:latest
  #   argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gaurav00700/llm_app-frontend:latest
        # imagePullPolicy: Always  # Always pulls the latest image when the pod restarts
        ports:
        - containerPort: 8500
        env:
        - name: BACKEND_ENDPNT
          value: "http://backend.llm-backend.svc.cluster.local:8000/ask"
        volumeMounts:
        - mountPath: /workdir/data
          name: data-volume
      volumes:  # Call the volume mount
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc   # Matches PVC name in the same namespace

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: llm-frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8500  # host port
    targetPort: 8500  # pod port
