apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: llm-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        # imagePullPolicy: Always  # Always pulls the latest image when the pod restarts
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-volume
      volumes:  # Call the volume mount
      - name: redis-volume
        persistentVolumeClaim:
          claimName: redis-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: llm-redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
