name: CI/CD for Ollama App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest fastapi uvicorn httpx requests redis
          # pip install pytest
          # pip install httpx

          
      - name: Run tests
        run: |
          pytest

  # build-backend:
  #   needs: test-backend
  #   runs-on: ubuntu-latest
  #   steps:     
  #     - name: Checkout code
  #       uses: actions/checkout@v4 

  #     - name: Build The Docker Image
  #       run: docker build . --file backend/Dockerfile --tag backend-test:$(date +%s)
      
  publish-backend:
    needs: test-backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/llm_app-backend:latest

    - name: Image digest
      run: echo ${{ steps.build-and-publish.outputs.digest }}