name: CI/CD for Ollama App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: /opt/pip-cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${runner.os}-pip-
      
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt
      
      - name: Run tests
        run: pytest

  build-backend:
    needs: test-backend
    runs-on: ubuntu-latest
    steps:
      - name: Use shared checkout
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('backend/Dockerfile') }}
      
      - name: Build Docker image
        run: docker build . --file backend/Dockerfile --tag llm_app-backend:latest
      
  publish-backend:
    needs: [test-backend, build-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Use shared checkout
        uses: actions/checkout@v4
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Push Docker image
        run: |
          docker push llm_app-backend:latest
      
      - name: Image digest
        run: echo ${{ steps.push.outputs.digest }}